<a href="https://colab.research.google.com/github/efreitas7923-bit/tech-challenge-fase2-grupo28/blob/main/TechChallenge1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tratamento dos Dados

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(file_path)
df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

In [ ]:
df = pd.read_csv ("/credit_record.csv")
df.head()

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

In [ ]:
col_translation = {
    'ID': 'ID',
    'MONTHS_BALANCE': 'MESES_SALDO',
    'STATUS': 'STATUS'
}

df = df.rename(columns=col_translation)

# Exibir as primeiras linhas com os nomes das colunas traduzidos
display(df.head())

        ID  MESES_SALDO STATUS
0  5001711            0      X
1  5001711           -1      0
2  5001711           -2      0
3  5001711           -3      0
4  5001712            0      C

In [ ]:
# Carrega o arquivo application_record.csv novamente em um novo DataFrame
df_application = pd.read_csv(file_path)

# Define o dicionário de tradução para as colunas do application_record.csv
app_col_translation = {
    'ID': 'ID',
    'CODE_GENDER': 'GENERO',
    'FLAG_OWN_CAR': 'POSSUI_CARRO',
    'FLAG_OWN_REALTY': 'POSSUI_IMOVEL',
    'CNT_CHILDREN': 'NUM_FILHOS',
    'AMT_INCOME_TOTAL': 'RENDA_TOTAL',
    'NAME_INCOME_TYPE': 'TIPO_RENDA',
    'NAME_EDUCATION_TYPE': 'NIVEL_EDUCACAO',
    'NAME_FAMILY_STATUS': 'STATUS_CIVIL',
    'NAME_HOUSING_TYPE': 'TIPO_MORADIA',
    'DAYS_BIRTH': 'DIAS_NASCIMENTO',
    'DAYS_EMPLOYED': 'DIAS_EMPREGADO',
    'FLAG_MOBIL': 'FLAG_CELULAR',
    'FLAG_WORK_PHONE': 'FLAG_TELEFONE_TRABALHO',
    'FLAG_PHONE': 'FLAG_TELEFONE',
    'FLAG_EMAIL': 'FLAG_EMAIL',
    'OCCUPATION_TYPE': 'TIPO_OCUPACAO',
    'CNT_FAM_MEMBERS': 'NUM_MEMBROS_FAMILIA'
}

# Renomeia as colunas do df_application
df_application = df_application.rename(columns=app_col_translation)

# Exibe as primeiras linhas do DataFrame com as colunas traduzidas
display(df_application.head())

,ID,GENERO,POSSUI_CARRO,POSSUI_IMOVEL,NUM_FILHOS,RENDA_TOTAL,TIPO_RENDA,NIVEL_EDUCACAO,STATUS_CIVIL,TIPO_MORADIA,DIAS_NASCIMENTO,DIAS_EMPREGADO,FLAG_CELULAR,FLAG_TELEFONE_TRABALHO,FLAG_TELEFONE,FLAG_EMAIL,TIPO_OCUPACAO,NUM_MEMBROS_FAMILIA
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

Vamos garantir que a coluna `NUM_MEMBROS_FAMILIA` seja do tipo `int64`.

In [ ]:
# Converte a coluna 'NUM_MEMBROS_FAMILIA' de float64 para int64
df_application['NUM_MEMBROS_FAMILIA'] = df_application['NUM_MEMBROS_FAMILIA'].astype('int64')

# Exibe as informações atualizadas do DataFrame para confirmar a mudança
df_application.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ID                      438557 non-null  int64
 1   GENERO                  438557 non-null  object
 2   POSSUI_CARRO            438557 non-null  object
 3   POSSUI_IMOVEL           438557 non-null  object
 4   NUM_FILHOS              438557 non-null  int64
 5   RENDA_TOTAL             438557 non-null  float64
 6   TIPO_RENDA              438557 non-null  object
 7   NIVEL_EDUCACAO          438557 non-null  object
 8   STATUS_CIVIL            438557 non-null  object
 9   TIPO_MORADIA            438557 non-null  object
 10  DIAS_NASCIMENTO         438557 non-null  int64
 11  DIAS_EMPREGADO          438557 non-null  int64
 12  FLAG_CELULAR            438557 non-null  int64
 13  FLAG_TELEFONE_TRABALHO  438557 non-null  int64
 14  FLAG_TELEFONE           438557 non-null  int64
 15  FLAG_EMAIL              438557 non-null  int64
 16  TIPO_OCUPACAO           304354 non-null  object
 17  NUM_MEMBROS_FAMILIA     438557 non-null  int64
dtypes: float64(1), int64(9), object(8)
memory usage: 60.2+ MB

Vamos converter a coluna `DIAS_NASCIMENTO` para uma nova coluna `IDADE`, que representará a idade em anos.

In [ ]:
# Converte a coluna 'DIAS_NASCIMENTO' (que está em dias negativos) para 'IDADE' em anos.
# Dividimos por 365.25 para uma estimativa mais precisa considerando anos bissextos e convertemos para int.
df_application['IDADE'] = (-df_application['DIAS_NASCIMENTO'] / 365.25).astype('int64')

# Exibe as colunas 'DIAS_NASCIMENTO' e a nova coluna 'IDADE' para verificação
print('Colunas DIAS_NASCIMENTO e IDADE após a conversão:')
display(df_application[['DIAS_NASCIMENTO', 'IDADE']].head())

Colunas DIAS_NASCIMENTO e IDADE após a conversão:

   DIAS_NASCIMENTO  IDADE
0           -12005     32
1           -12005     32
2           -21474     58
3           -19110     52
4           -19110     52

Vamos converter a coluna `DIAS_EMPREGADO` em anos de emprego, criando uma nova coluna `ANOS_EMPREGADO`. Consideraremos também a condição da coluna `TIPO_OCUPACAO` e o valor especial de `DIAS_EMPREGADO` (365243).

conversão dos dias de nascimento em Idade (anos)

In [ ]:
display(df_application.head())

,ID,GENERO,POSSUI_CARRO,POSSUI_IMOVEL,NUM_FILHOS,RENDA_TOTAL,TIPO_RENDA,NIVEL_EDUCACAO,STATUS_CIVIL,TIPO_MORADIA,DIAS_NASCIMENTO,DIAS_EMPREGADO,FLAG_CELULAR,FLAG_TELEFONE_TRABALHO,FLAG_TELEFONE,FLAG_EMAIL,TIPO_OCUPACAO,NUM_MEMBROS_FAMILIA
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1

In [ ]:
display(df_application.head())

,ID,GENERO,POSSUI_CARRO,POSSUI_IMOVEL,NUM_FILHOS,RENDA_TOTAL,TIPO_RENDA,NIVEL_EDUCACAO,STATUS_CIVIL,TIPO_MORADIA,DIAS_NASCIMENTO,DIAS_EMPREGADO,FLAG_CELULAR,FLAG_TELEFONE_TRABALHO,FLAG_TELEFONE,FLAG_EMAIL,TIPO_OCUPACAO,NUM_MEMBROS_FAMILIA,IDADE
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2,32
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2,32
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2,58
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1,52
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1,52

In [ ]:
import numpy as np

# Cria uma nova coluna 'ANOS_EMPREGADO' inicializada com NaN (Not a Number)
df_application['ANOS_EMPREGADO'] = np.nan

# Preenche 'ANOS_EMPREGADO' para casos em que DIAS_EMPREGADO é 365243 (geralmente significa desempregado)
df_application.loc[df_application['DIAS_EMPREGADO'] == 365243, 'ANOS_EMPREGADO'] = 0

# Preenche 'ANOS_EMPREGADO' para os dias de emprego normais (valores negativos)
# Apenas para as linhas onde DIAS_EMPREGADO é negativo e ANOS_EMPREGADO ainda não foi definido (não é 0)
mask_empregado = (df_application['DIAS_EMPREGADO'] < 0) & (df_application['ANOS_EMPREGADO'].isnull())
df_application.loc[mask_empregado, 'ANOS_EMPREGADO'] = ((-df_application.loc[mask_empregado, 'DIAS_EMPREGADO']) / 365.25).astype(int)

# Aplica a condição: se TIPO_OCUPACAO estiver vazio, defina ANOS_EMPREGADO como "Não informado"
df_application.loc[df_application['TIPO_OCUPACAO'].isnull(), 'ANOS_EMPREGADO'] = "Não informado"

# Exibe as colunas relevantes para verificação
print('Colunas DIAS_EMPREGADO, TIPO_OCUPACAO e ANOS_EMPREGADO após as transformações:')
display(df_application[['DIAS_EMPREGADO', 'TIPO_OCUPACAO', 'ANOS_EMPREGADO']].head(10))

Colunas DIAS_EMPREGADO, TIPO_OCUPACAO e ANOS_EMPREGADO após as transformações:

/tmp/ipykernel_1537/674312768.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Não informado' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_application.loc[df_application['TIPO_OCUPACAO'].isnull(), 'ANOS_EMPREGADO'] = "Não informado"

   DIAS_EMPREGADO   TIPO_OCUPACAO ANOS_EMPREGADO
0           -4542             NaN  Não informado
1           -4542             NaN  Não informado
2           -1134  Security staff            3.0
3           -3051     Sales staff            8.0
4           -3051     Sales staff            8.0
5           -3051     Sales staff            8.0
6           -3051     Sales staff            8.0
7          365243             NaN  Não informado
8          365243             NaN  Não informado
9          365243             NaN  Não informado

In [ ]:
display(df_application.head())

,ID,GENERO,POSSUI_CARRO,POSSUI_IMOVEL,NUM_FILHOS,RENDA_TOTAL,TIPO_RENDA,NIVEL_EDUCACAO,STATUS_CIVIL,TIPO_MORADIA,DIAS_NASCIMENTO,DIAS_EMPREGADO,FLAG_CELULAR,FLAG_TELEFONE_TRABALHO,FLAG_TELEFONE,FLAG_EMAIL,TIPO_OCUPACAO,NUM_MEMBROS_FAMILIA,IDADE,ANOS_EMPREGADO
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2,32,Não informado
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2,32,Não informado
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2,58,3.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1,52,8.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1,52,8.0